name: Update README

permissions:
  contents: write  # allow workflow to push changes back

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # every day at 07:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater script
        run: python update_readme.py

      - name: Commit & push if README changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain README.md) ]]; then
            git add README.md
            git commit -m "chore: automated README update [skip ci]"
            git push
          fi
